# Homework 3

1\. Add shifts to the QR algorithm

Instead of factoring $A_k$ as $Q_k R_k$ (the way the pure QR algorithm without shifts does), the shifted QR algorithms:

i. Get the QR factorization $$A_k - s_k I = Q_k R_k$$
ii. Set $$A_{k+1} = R_k Q_k + s_k I$$

Choose $s_k = A_k(m,m)$, an approximation of an eigenvalue of A. 

The idea of adding shifts to speed up convergence shows up in many algorithms in numerical linear algebra (including the power method, inverse iteration, and Rayleigh quotient iteration).   

In [2]:
import numpy as np

In [3]:
n = 6
A = np.random.rand(n,n)
AT = A @ A.T

In [15]:
def practical_qr(A, max_iter=50000):
    Ak = np.copy(A)
    n = A.shape[0]
    QQ = np.eye(n)
    m = np.random.randint(0, n)
    for k in range(max_iter):
        shift = np.identity(n) * Ak[m,m]
        Q, R = np.linalg.qr(Ak - shift)
        Ak = R @ Q + shift
        QQ = QQ @ Q
        if k % 100 == 0:
            print(Ak)
            print("\n")
    return Ak, QQ

In [16]:
Ak, Q = practical_qr(A)

[[ 1.05654368  1.09020033  0.6077493  -1.04678747 -0.31237423 -0.209133  ]
 [ 1.2197466   0.62245293  0.34980274 -0.61128676 -0.15978416 -0.12225013]
 [ 1.1429185   0.57917012 -0.00971726 -0.71509049 -0.17860468  0.07841738]
 [-0.71954816 -0.1528837  -0.27973215  0.46152401  0.0598771  -0.19061849]
 [ 0.05527584  0.03367096  0.04638834  0.0307907   0.66238656  0.04098851]
 [-0.02116631  0.00787825 -0.01769705 -0.00529045  0.01519432  0.71405888]]


[[ 2.78821147e+000 -4.52856408e-001 -6.05377982e-001 -1.57550115e-001
   4.70424985e-001 -4.89823051e-001]
 [ 3.27626682e-037 -5.48421280e-001  5.30086305e-002 -1.92135747e-001
  -9.34557011e-002 -2.25880407e-002]
 [ 6.84052833e-050 -8.01956189e-014 -3.02471985e-001  1.16393239e-001
  -1.66955210e-002 -1.05114979e-001]
 [ 3.74228496e-098 -2.80768827e-061  5.04606515e-049  5.23233043e-001
   3.96117679e-001  1.52829593e-002]
 [ 2.72040173e-099 -8.20395908e-062  1.52663593e-049  1.69452153e-001
   3.82159083e-001 -7.83732774e-003]
 [-1.9757367

In [17]:
Ak

array([[ 2.78821147e+000,  4.52856408e-001,  6.05377982e-001,
        -4.70424985e-001, -1.57550115e-001, -4.89823051e-001],
       [ 0.00000000e+000, -5.48421280e-001,  5.30086305e-002,
        -9.34557011e-002,  1.92135747e-001,  2.25880407e-002],
       [ 0.00000000e+000,  0.00000000e+000, -3.02471985e-001,
        -1.66955210e-002, -1.16393239e-001,  1.05114979e-001],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         3.82159083e-001, -1.69452153e-001,  7.83732774e-003],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        -3.96117679e-001,  5.23233043e-001,  1.52829593e-002],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        -4.94065646e-324, -4.94065646e-324,  6.64538479e-001]])

In [11]:
np.linalg.eigvals(A)

array([ 2.78821147, -0.54842128, -0.30247198,  0.1841845 ,  0.72120763,
        0.66453848])

In [12]:
np.allclose(np.eye(n), Q @ Q.T), np.allclose(np.eye(n), Q.T @ Q)

(True, True)