## Homework 2

This homework covers the material in Lessons 3 & 4.  It is due **Thurday, June 15**.  Please submit your **answers as a PDF**.

1\. Modify the LU method (without pivoting) to work **in-place**.  That is, it should not allocate any new memory for L or U, but instead overwrite A.

In [1]:
import numpy as np

In [137]:
A = np.array([[1e-20, 1], [1,1]])

In [138]:
def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
    return L, U

In [139]:
LU(A)

(array([[1.e+00, 0.e+00],
        [1.e+20, 1.e+00]]),
 array([[ 1.e-20,  1.e+00],
        [ 0.e+00, -1.e+20]]))

In [140]:
def LUInplace(A):
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = A[j,k]/A[k,k]
            A[j,k:n] -= L[j,k] * A[k,k:n]
    return L, A

In [129]:
LUInplace(A)

In [119]:
A = np.array([[1e-20, 1], [1,1]])
A

array([[1.e-20, 1.e+00],
       [1.e+00, 1.e+00]])

In [120]:
def swap(a,b):
    temp = np.copy(a)
    a[:] = b
    b[:] = temp

In [121]:
def LUPivot(A):
    U = np.copy(A)
    print(U)
    m, n = U.shape
    L = np.eye(n)
    for k in range(n-1):
        maxPosition = np.argmax(U[:,k])
        swap(U[maxPosition],U[k])
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
        
    return L, U

In [123]:
a , b = LUPivot(A)

[[1.e-20 1.e+00]
 [1.e+00 1.e+00]]
1
[[1.e+00 1.e+00]
 [1.e-20 1.e+00]]


In [126]:
b

array([[1., 1.],
       [0., 1.]])

In [124]:
np.matmul(a,b)

array([[1.e+00, 1.e+00],
       [1.e-20, 1.e+00]])

3\. For each of the following sets of dimensions, either
  - give the dimensions of the output of an operation on A and B, **or** 
  - answer *incompatible* if the dimensions are incompatible according to the [numpy rules of broadcasting](https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html).

    a.  A      (2d array):  3 x 3
        B      (1d array):      1

    b.  A      (2d array):      2 x 1
        B      (3d array):  6 x 4 x 2

    c.  A      (2d array):  5 x 4
        B      (1d array):      4

    d.  A      (3d array):  32 x 64 x 8
        B      (3d array):   32 x 1 x 8

    e.  A      (3d array):       64 x 1
        B      (3d array):  32 x 1 x 16

    f.  A      (3d array):  32 x 64 x 2
        B      (3d array):   32 x 1 x 8

3.
a) 3 X 3

b) incomptabile

c) 5 x 4

d) 32 x 64 x 8

e) 32 x 64 x 16

f) incompatible

4\. Write how this matrix would be stored in compressed row format:

\begin{pmatrix}
  1 & & & & -2 & -3 \\
  & 3 &  & & & -9 \\
  &  &  & -7 & 4 & \\ 
  -1 & 2 & & 7 & & \\
  -3 & & & 26 & &
 \end{pmatrix}